version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: gomarket
      POSTGRES_DB: gomarket
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    name: postgres_volume_gomarket
    driver: local
